import pandas as pd
import os
'''
def delete_header(filepath, filename, num_lines):
    
    # Deletes the column headings made by opal 
    # Be careful to only call use delete_header when the header is actully there
    # otherwise it will delete the first line(s) of data
    

    with open(filepath + filename, 'r') as fin:
        data = fin.read().splitlines(True)

    if data[0][0] == '#' and data[0][1] == ' ':
        with open(filepath + filename, 'w') as fout:
            fout.writelines(data[num_lines:])
'''
def read_trackOrbit(filepath, filename):
    '''
    Reads the trackOrbit file into a pandas dataframe with the proper column headings
    '''
    #delete_header(filepath, filename, num_lines=2)

    dataframe = pd.read_csv(os.path.join(filepath, filename), delim_whitespace=True, header=None, skiprows=range(0,2))
    dataframe.columns = ['# Part. ID','x [m]','beta_x*gamma','y [m]','beta_y*gamma','z [m]','beta_z*gamma']
    

    return dataframe

def read_Angle(filepath, filename):
    '''
    Reads the Angle file into a pandas dataframe with the proper column headings
    Note; the pandas data frame will exlcude the turn numbers and times generated by opal
    '''

    #delete_header(filepath, filename, num_lines=1)
    
    dataframe = pd.read_csv(os.path.join(filepath, filename), delim_whitespace=True, header=None, skiprows=range(0,2), error_bad_lines=False)

    dataframe = dataframe.drop(range(0, dataframe.shape[0], 2))
    dataframe = dataframe.drop(columns=[6, 7])

    dataframe.columns = ['r [mm]','beta_r*gamma','theta [deg]','beta_theta*gamma','z [mm]','beta_z*gamma']

    return dataframe

def read_probe(filepath, filename):
    #   # x (m),  y (m),  z (m),  px ( ),  py ( ),  pz ( ), id,  turn ( ), bunchNumber ( ), time (s)
    dataframe = pd.read_csv(os.path.join(filepath, filename), delim_whitespace=True,header=None, skiprows=range(0,1))
    dataframe.columns = ['# x (m)',  'y (m)', ' z (m)',  'px ( )',  'py ( )',  'pz ( )', 'id',  'turn ( )', 'bunchNumber ( )', 'time (s)']

    return dataframe

def read_FieldMap(filepath, filename):

    dataframe = pd.read_csv(os.path.join(filepath, filename), delim_whitespace=True, header=None,skiprows=range(0,13))
    
    #dataframe.columns = ['x [mm]','y [mm]','z [mm]','t [ns]','Bx [kGauss]','By [kGauss]', 'Bz [kGauss]', 'Ex [MV/m]', 'Ey [MV/m]', 'Ez [MV/m]']
    #dataframe.columns = ['x [mm]','y [mm]','z [mm]','Bx [kGauss]','By [kGauss]', 'Bz [kGauss]']
    dataframe.columns = ['x [m]','y [m]','z [m]','Bx [kGauss]','By [kGauss]', 'Bz [kGauss]']
    return dataframe

def read_FieldMapRPHI(filepath, filename):

    dataframe = pd.read_csv(os.path.join(filepath, filename), delim_whitespace=True, header=None,skiprows=range(0,12))
    
    #dataframe.columns = ['x [mm]','y [mm]','z [mm]','t [ns]','Bx [kGauss]','By [kGauss]', 'Bz [kGauss]', 'Ex [MV/m]', 'Ey [MV/m]', 'Ez [MV/m]']
    #dataframe.columns = ['x [mm]','y [mm]','z [mm]','Bx [kGauss]','By [kGauss]', 'Bz [kGauss]']
    dataframe.columns = ['r [mm]','phi [degree]','z [mm]','t [ns]','Br [kGauss]','Bphi [kGauss]','Bz [kGauss]','Er [MV/m]','Ephi [MV/m]','Ez [MV/m]']
    return dataframe

